---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ans1
  labels:
    app: "ans1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "ans1"
  template:
    metadata:
      labels:
        app: "ans1"
    spec:
      containers:
      - name: ans1
        # image: chrismeyers/centos7
        # image: rzabcio/centos7-ansible
        image: rzabcio/centos7-ansible2
        ports:
        - containerPort: 80
        - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: ans1
  labels:
    app: "ans1"
spec:
  type: NodePort
  ports:
  - name: ssh
    port: 22
    targetPort: 22
    nodePort: 30122
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30180

